### ISSUE TITLE
第一次选中打开的时候 没有代码回显

### ISSUE THREAD

**Issue by ZHDLFFY** [subframe7536/vscode-codeimg#1]
第一次:  选中一串代码  ---> 鼠标右键打开选项 ---> 点击CodeImg:generate ---> vscode右侧出现codeimg窗口 ----> 此时窗口中只有基本的样式，没有选中的代码 ------> 重新选中一串代码，再次点击CodeImg:generate，代码才会成功回显

**Comment by subframe7536** [comment]
可以录个屏吗？没法复现

另外试一下出现窗口后重新选择代码

还有你的 VSCode 版本号
